/**
 * Bumelerze Atlas index (D21) — GENERATED by
 * shake-service/scripts/bundle_atlas_for_app.py — do not hand-edit.
 * Regenerate: ./.venv/bin/python scripts/bundle_atlas_for_app.py
 * (from shake-service/), after re-running seed_atlas.py.
 *
 * Maps every curated historical event id
 * (src/features/historical/notable-events.ts) to its bundled
 * bumelerze-shake-service product — raw cont_mi.json contours +
 * review_status + a data-used summary key, computed entirely
 * offline (shake-service/scripts/seed_atlas.py), zero network cost
 * at render time (D21: "Displayed maps are ALWAYS
 * bumelerze-shake-service products").
 */
import type { AtlasBundleEntry } from "../types";

import atlas_iscgem899464 from "./data/iscgem899464.json";
import atlas_iscgem898547 from "./data/iscgem898547.json";
import atlas_iscgem884317 from "./data/iscgem884317.json";
import atlas_iscgem839648 from "./data/iscgem839648.json";
import atlas_usp0001bb6 from "./data/usp0001bb6.json";
import atlas_usp0004uk3 from "./data/usp0004uk3.json";
import atlas_us2000bmcg from "./data/us2000bmcg.json";
import atlas_us1000ghda from "./data/us1000ghda.json";
import atlas_us1000hwdw from "./data/us1000hwdw.json";
import atlas_us6000jllz from "./data/us6000jllz.json";
import atlas_us6000jlqa from "./data/us6000jlqa.json";

export const ATLAS_INDEX: Readonly<Record<string, AtlasBundleEntry>> = {
  "iscgem899464": atlas_iscgem899464 as unknown as AtlasBundleEntry,
  "iscgem898547": atlas_iscgem898547 as unknown as AtlasBundleEntry,
  "iscgem884317": atlas_iscgem884317 as unknown as AtlasBundleEntry,
  "iscgem839648": atlas_iscgem839648 as unknown as AtlasBundleEntry,
  "usp0001bb6": atlas_usp0001bb6 as unknown as AtlasBundleEntry,
  "usp0004uk3": atlas_usp0004uk3 as unknown as AtlasBundleEntry,
  "us2000bmcg": atlas_us2000bmcg as unknown as AtlasBundleEntry,
  "us1000ghda": atlas_us1000ghda as unknown as AtlasBundleEntry,
  "us1000hwdw": atlas_us1000hwdw as unknown as AtlasBundleEntry,
  "us6000jllz": atlas_us6000jllz as unknown as AtlasBundleEntry,
  "us6000jlqa": atlas_us6000jlqa as unknown as AtlasBundleEntry,
};

export const ATLAS_EVENT_IDS: readonly string[] = Object.keys(ATLAS_INDEX);
