import { NOTABLE_PROVIDER_ID_BY_BUMELERZE_ID } from "@/features/historical";

/**
 * Resolves the key `useShakeMap` should look `ATLAS_INDEX` up by, given an
 * event that may now be identified by its `bml` id rather than the
 * provider id the (generated, provider-id-keyed) bundle still uses
 * (`atlas/index.ts`'s own header: "do not hand-edit" — regenerated by
 * `bumelerze-engine/scripts/bundle_atlas_for_app.py`, not something this
 * app-side wave touches). "bml first through the notable mapping, then
 * provider id" (wave brief): a bml id that names one of the 11 curated
 * Historical events maps straight back to its bundled provider-id key,
 * offline, no network — every other event (bml id unknown/not curated, or
 * no bml id resolved yet) falls through to its own `id` unchanged, exactly
 * `useShakeMap`'s pre-existing behaviour.
 */
export function resolveAtlasLookupId(event: {
  id: string;
  bumelerzeId: string | null;
}): string {
  if (event.bumelerzeId) {
    const providerId = NOTABLE_PROVIDER_ID_BY_BUMELERZE_ID.get(event.bumelerzeId);
    if (providerId) {
      return providerId;
    }
  }
  return event.id;
}
