import { useMemo } from "react";

import { ATLAS_INDEX } from "./atlas";
import { parseIntensityContours } from "./contours";
import type { AtlasBundleEntry, IntensityContourSet } from "./types";

/**
 * Bundled-only ShakeMap lookup (D21, `docs/decisions.md`: "Displayed
 * maps are ALWAYS bumelerze-shake-service products ... USGS ShakeMap
 * products are never user-facing" — the live USGS fetch path
 * (`usgs-products.ts`, `fetchIntensityContours`) was REMOVED this wave,
 * app-side; the service now reads USGS data itself and produces OUR
 * product instead, D21 point 2). `ATLAS_INDEX` (`atlas/index.ts`,
 * generated by `shake-service/scripts/bundle_atlas_for_app.py`) is a
 * static bundle — no network, no React Query, a lookup is synchronous.
 *
 * Only the Bumelerze Atlas's curated events have a bundled product today
 * (D21 point 5, "interim display default": "where our product doesn't
 * exist yet, the ShakeMap section shows nothing — absence over
 * misattribution") — every other event resolves to `"absent"`, same as
 * the old "no ShakeMap product" case, until the worker's own auto-grown
 * Atlas entries are synced into a future bundle/fetch path.
 */

export type UseShakeMapStatus = "absent" | "ready";

export interface UseShakeMapResult {
  status: UseShakeMapStatus;
  product: AtlasBundleEntry | null;
  contours: IntensityContourSet | null;
}

const ABSENT: UseShakeMapResult = { status: "absent", product: null, contours: null };

/**
 * `enabled` is kept for call-site compatibility (`ShakeMapSection` mounts
 * this unconditionally today) even though nothing here is actually async
 * anymore — a disabled/empty-id lookup is just `"absent"`, not a
 * distinct "loading" state (there is nothing to wait for).
 */
export function useShakeMap(eventId: string, enabled: boolean): UseShakeMapResult {
  return useMemo(() => {
    if (!enabled || !eventId) {
      return ABSENT;
    }
    const entry = ATLAS_INDEX[eventId];
    if (!entry) {
      return ABSENT;
    }
    const contours = parseIntensityContours(entry.contours);
    return { status: "ready", product: entry, contours };
  }, [eventId, enabled]);
}
