import { useMemo } from "react";

import { ATLAS_INDEX } from "./atlas";
import { parseIntensityContours } from "./contours";
import { parseRiskProduct } from "./risk";
import type { AtlasBundleEntry, IntensityContourSet, RiskProduct } from "./types";

/**
 * Bundled-only shakemap lookup (D21, `docs/decisions.md`: "Displayed
 * maps are ALWAYS bumelerze-engine products ... USGS ShakeMap
 * products are never user-facing" — the live USGS fetch path
 * (`usgs-products.ts`, `fetchIntensityContours`) was REMOVED this wave,
 * app-side; the service now reads USGS data itself and produces OUR
 * product instead, D21 point 2). `ATLAS_INDEX` (`atlas/index.ts`,
 * generated by `bumelerze-engine/scripts/bundle_atlas_for_app.py`) is a
 * static bundle — no network, no React Query, a lookup is synchronous.
 *
 * Only the Bumelerze Atlas's curated events have a bundled product —
 * every other event resolves to `"absent"` HERE, same as the old "no
 * shakemap product" case. This hook stays exactly that narrow on purpose:
 * `ShakeMapSection` does not call it directly anymore — it calls
 * `live-queries.ts`'s `useResolvedShakeMap`, which composes this bundled
 * lookup with the live `shakemap_products` lookup
 * (`live-queries.ts`/`live-transport.ts`) through `resolver.ts`'s
 * precedence rule ("closing the last gap in the SHAKEmap pipeline" wave —
 * the worker's uploader now publishes every computed event, not just the
 * 11 curated ones, this hook's own "every other event resolves to absent"
 * limitation above is what that wave closes at the app layer).
 */

export type UseShakeMapStatus = "absent" | "ready";

export interface UseShakeMapResult {
  status: UseShakeMapStatus;
  product: AtlasBundleEntry | null;
  contours: IntensityContourSet | null;
  /** `null` for the common case (no bundled risk product for this event) —
   * see `AtlasBundleEntry.risk`'s own doc comment. */
  risk: RiskProduct | null;
}

const ABSENT: UseShakeMapResult = { status: "absent", product: null, contours: null, risk: null };

/**
 * `enabled` is kept for call-site compatibility (`ShakeMapSection` mounts
 * this unconditionally today) even though nothing here is actually async
 * anymore — a disabled/empty-id lookup is just `"absent"`, not a
 * distinct "loading" state (there is nothing to wait for).
 */
export function useShakeMap(eventId: string, enabled: boolean): UseShakeMapResult {
  return useMemo(() => {
    if (!enabled || !eventId) {
      return ABSENT;
    }
    const entry = ATLAS_INDEX[eventId];
    if (!entry) {
      return ABSENT;
    }
    const contours = parseIntensityContours(entry.contours);
    const risk = entry.risk !== undefined ? parseRiskProduct(entry.risk) : null;
    return { status: "ready", product: entry, contours, risk };
  }, [eventId, enabled]);
}
