/**
 * Bundled Bumelerze Atlas product contract (D21: "Displayed maps are
 * ALWAYS bumelerze-engine products ... USGS ShakeMap products are
 * never user-facing"). `atlas/index.ts` (generated by
 * `bumelerze-engine/scripts/bundle_atlas_for_app.py`) is the only module that
 * knows the bundle's on-disk JSON shape; everything past it reads
 * `AtlasBundleEntry`. There is deliberately no USGS-shaped product type
 * anymore — the live USGS ShakeMap display path was removed this wave (see
 * `queries.ts`'s doc comment).
 */

/** D21 "scientist-review status" (provenance-as-UI) — every bundled
 * product carries one. */
export type ReviewStatus = "automatic" | "reviewed";

/** Coarse, translatable summary of what conditioned a bundled product —
 * computed at bundle-generation time from the service's own
 * `info.json.data_used.conditioning_applied` flags (honest about the
 * small-N conditioning floor: an event with raw station/DYFI data that
 * never cleared the floor is `"catalogOnly"`, not falsely labelled
 * conditioned). Each value maps 1:1 to an
 * `eventDetail.shakemap.dataUsed.*` i18n key. */
export type DataUsedSummaryKey =
  "catalogOnly" | "stationConditioned" | "dyfiConditioned" | "stationAndDyfiConditioned";

/** One Bumelerze Atlas bundle entry — `bumelerze-engine/scripts/
 * bundle_atlas_for_app.py`'s generated output, statically imported by
 * `atlas/index.ts`. */
export interface AtlasBundleEntry {
  eventId: string;
  producer: "bumelerze";
  /** Product version number (`info.json.product_version` from the
   * service). */
  version: number;
  reviewStatus: ReviewStatus;
  dataUsedSummaryKey: DataUsedSummaryKey;
  /** Product generation time, ISO 8601 (`info.json.generated_at`). */
  generatedAt: string;
  /** Raw `cont_mi.json`-shaped GeoJSON (the service's own `export.py`
   * output, byte-identical) — parsed via `parseIntensityContours` at
   * render time, same schema/validation path a future live product would
   * go through (never trusted blindly just because it's bundled). */
  contours: unknown;
}

/** One MMI contour ring: a sequence of `[lon, lat]` points (GeoJSON
 * coordinate order preserved end to end so `projection.ts` never has to
 * remember which axis is which). Never assumed closed — `ShakeMapView`
 * relies on SVG `Polygon`'s own auto-close behavior rather than requiring
 * `points[0] === points[last]`. */
export interface ContourRing {
  points: readonly (readonly [number, number])[];
}

/** All rings sharing one MMI value, plus the ramp-index this value maps to
 * (`level`, 1..12 — see `intensity-ramp.ts`). */
export interface IntensityContourLevel {
  /** Raw MMI value as reported by the product — may be fractional (USGS
   * `cont_mi.json` commonly emits half-integer levels like 4.5). */
  value: number;
  /** `value` rounded and clamped to the EMS-98/MMI ramp's 1..12 index
   * range (D7) — the index into `theme.colors.intensity`. */
  level: number;
  rings: ContourRing[];
}

/** Producer-agnostic parsed contour product (D9: "our service exports the
 * same shape" later). Always sorted ascending by `value` so a renderer that
 * simply iterates and paints in order gets correct z-ordering (higher
 * intensities paint last, on top of lower ones) for free. */
export interface IntensityContourSet {
  levels: IntensityContourLevel[];
  /** Count of contour features present in the source payload that failed
   * schema validation and were skipped — tolerant-parsing bookkeeping,
   * same convention as `events/usgs.ts`'s `skippedCount`. */
  skippedCount: number;
}
