/**
 * Bundled Bumelerze Atlas product contract (D21: "Displayed maps are
 * ALWAYS bumelerze-engine products ... USGS ShakeMap products are
 * never user-facing"). `atlas/index.ts` (generated by
 * `bumelerze-engine/scripts/bundle_atlas_for_app.py`) is the only module that
 * knows the bundle's on-disk JSON shape; everything past it reads
 * `AtlasBundleEntry`. There is deliberately no USGS-shaped product type
 * anymore — the live USGS ShakeMap display path was removed this wave (see
 * `queries.ts`'s doc comment).
 */

/** D21 "scientist-review status" (provenance-as-UI) — every bundled
 * product carries one. */
export type ReviewStatus = "automatic" | "reviewed";

/** Coarse, translatable summary of what conditioned a bundled product —
 * computed at bundle-generation time from the service's own
 * `info.json.data_used.conditioning_applied` flags (honest about the
 * small-N conditioning floor: an event with raw station/DYFI data that
 * never cleared the floor is `"catalogOnly"`, not falsely labelled
 * conditioned). Each value maps 1:1 to an
 * `eventDetail.shakemap.dataUsed.*` i18n key. */
export type DataUsedSummaryKey =
  "catalogOnly" | "stationConditioned" | "dyfiConditioned" | "stationAndDyfiConditioned";

/** One Bumelerze Atlas bundle entry — `bumelerze-engine/scripts/
 * bundle_atlas_for_app.py`'s generated output, statically imported by
 * `atlas/index.ts`. */
export interface AtlasBundleEntry {
  eventId: string;
  producer: "bumelerze";
  /** Product version number (`info.json.product_version` from the
   * service). */
  version: number;
  reviewStatus: ReviewStatus;
  dataUsedSummaryKey: DataUsedSummaryKey;
  /** Product generation time, ISO 8601 (`info.json.generated_at`). */
  generatedAt: string;
  /** Raw `cont_mi.json`-shaped GeoJSON (the service's own `export.py`
   * output, byte-identical) — parsed via `parseIntensityContours` at
   * render time, same schema/validation path a future live product would
   * go through (never trusted blindly just because it's bundled). */
  contours: unknown;
  /** Optional risk-chain bundle (D46 damage/exposure products,
   * `risk-dashboard` wave): `{ summary, districts, damageContours?, areas? }`,
   * each raw and byte-identical to the engine's own `risk_summary.json`/
   * `districts.json`/`cont_damage.json`/`areas.json` — parsed via `risk.ts`'s
   * `parseRiskProduct` at render/resolve time, same "never trust blindly"
   * discipline `contours` above already follows. Present only for events
   * that actually have a real risk product computed (three at launch:
   * us6000jllz, us6000jlqa, us2000bmcg); absent (`undefined`) for every
   * other bundled event — never a fabricated empty shell. `areas` is newer
   * than the other three (`risk-areas` wave) — a bundled entry generated
   * before that wave simply carries no `areas` key at all, which
   * `parseRiskProduct` already treats identically to a missing
   * `damageContours` key: the product still parses, `areas` just resolves
   * to `null`. */
  risk?: unknown;
}

/** One contour ring: a sequence of `[lon, lat]` points (GeoJSON
 * coordinate order preserved end to end so `projection.ts` never has to
 * remember which axis is which). The final point need not repeat the
 * first; renderers close the outline themselves.
 *
 * `closed` says whether the ring bounds a region at all. A filled band
 * from `bands_mi.json` always does. A line from a `cont_mi.json`-style
 * product does only if it did not run off the edge of the producer's
 * grid: an open path has no interior, and joining its two ends to invent
 * one draws a chord across open space. Renderers must stroke an open ring
 * and fill only closed ones.
 *
 * `holes` are interior rings cut out of `points`, so a band with a
 * low-intensity island in it shows the band below through the gap instead
 * of painting over it. Only filled-polygon products carry them. */
export interface ContourRing {
  points: readonly (readonly [number, number])[];
  closed?: boolean;
  holes?: readonly (readonly (readonly [number, number])[])[];
}

/**
 * One IMS-25 building type's damage. Product schema 2.
 *
 * `shareHeavy` is the fraction of THIS type's own stock heavily damaged,
 * and it is the number that carries the vulnerability model's statement.
 * A count on its own hides it: on the 2017 event manufactured stone with
 * concrete floors has the second highest count of heavy damage in the
 * country purely because there is so much of it, at 0.2 percent of its
 * own stock, while rubble-stone masonry sits at 2.5 percent.
 */
export interface RiskBuildingTypeDamage {
  /** IMS-25 type code, the key into `RiskTypeCatalog`. */
  code: string;
  buildings: number;
  /** Buildings of this type at damage grade 3 or worse. */
  buildingsHeavy: number;
  /** `buildingsHeavy / buildings`, 0..1. */
  shareHeavy: number;
  /** DG0..DG5 counts; carried nationally and per governorate only. */
  buildingsByGrade: readonly number[] | null;
}

/** IMS-25 type metadata, carried once per product rather than on every
 * row of every area (which tripled the product). Keyed by type code. */
export type RiskTypeCatalog = Readonly<
  Record<string, { group: string; description: string; vulnerabilityClass: string }>
>;

/** People by whole IMS-25 intensity degree, keyed by degree (5 = "V").
 * Product schema 2, and the replacement for "people in the shaken area",
 * which counted everyone inside the map window. */
export type RiskPopulationByIntensity = Readonly<Record<number, number>>;

/** All rings sharing one MMI value, plus the ramp-index this value maps to
 * (`level`, 1..12 — see `intensity-ramp.ts`). */
export interface IntensityContourLevel {
  /** Raw MMI value as reported by the product — may be fractional (USGS
   * `cont_mi.json` commonly emits half-integer levels like 4.5). */
  value: number;
  /** `value` rounded and clamped to the EMS-98/MMI ramp's 1..12 index
   * range (D7) — the index into `theme.colors.intensity`. */
  level: number;
  rings: ContourRing[];
}

/** Producer-agnostic parsed contour product (D9: "our service exports the
 * same shape" later). Always sorted ascending by `value` so a renderer that
 * simply iterates and paints in order gets correct z-ordering (higher
 * intensities paint last, on top of lower ones) for free. */
export interface IntensityContourSet {
  levels: IntensityContourLevel[];
  /** Count of contour features present in the source payload that failed
   * schema validation and were skipped — tolerant-parsing bookkeeping,
   * same convention as `events/usgs.ts`'s `skippedCount`. */
  skippedCount: number;
}

/**
 * Risk-chain product types (D46, `risk-dashboard` wave) — parsed by
 * `risk.ts`'s tolerant parsers, read by `RiskSection`. Field names are
 * camelCased app-side; the underlying JSON (`risk_summary.json`,
 * `districts.json`, `cont_damage.json`) is snake_case, same convention
 * `live-types.ts`'s `EngineVersionSummary` already follows for its own
 * source JSON. Deliberately narrower than the full source products —
 * only the fields `RiskSection`/`ShakeMapView`'s damage layer actually
 * read; casualty/fatality fields are never modelled here at all (D45:
 * "casualty estimates are computed but not published" — nothing to parse
 * even if a future product version added one, since this type has no slot
 * for it). */

export type RiskTimeOfDay = "day" | "night" | "transit";

/** `risk_summary.json`'s `exposure` block, narrowed to what the
 * provenance block/headline actually cite. */
export interface RiskExposure {
  buildingsInGrid: number;
  countries: readonly string[];
}

/** Parsed `risk_summary.json` (national/event-wide totals + the run's own
 * settings) — one per event version, alongside `RiskDistricts` and an
 * optional `DamageContourSet`. */
export interface RiskSummary {
  generatedAt: string;
  /** Fragility/hazard-conditioning stage id (e.g. `"pga_lognormal"`) —
   * shown verbatim in the provenance block, not translated (an internal
   * pipeline-stage identifier, same treatment `dataUsedSummaryKey` gives
   * OTHER provenance strings that ARE translated — this one is closer to a
   * version tag than a sentence). */
  stage: string;
  timeOfDay: RiskTimeOfDay;
  /** Monte Carlo draw count backing every P05/P50/P95 range in this
   * product (`mc_settings.n_samples_config` upstream). */
  nDraws: number;
  /** `hazard_version.conditioning`'s human-readable method string, e.g.
   * "mvn (Engler et al. 2022) on stations+dyfi..." — `null` when the
   * source product doesn't carry it (older/differently-shaped runs),
   * mirroring `EngineVersionSummary`'s own "never fabricated" rule. */
  hazardVersionConditioning: string | null;
  exposure: RiskExposure;
  /** Buildings at DG3+ (heavily damaged or worse), point estimate — the
   * headline number. */
  buildingsHeavy: number;
  /** [P05, P50, P95] of `buildingsHeavy` across the Monte Carlo draws. */
  buildingsHeavyP05P50P95: readonly [number, number, number];
  exposedPopulation: number;
  /** Always `false` today (D45's own publish gate) — read only so a
   * provenance line can say so; never gates displaying any casualty
   * number, because none is ever parsed in the first place. */
  casualtiesPublished: boolean;
  /** DG0..DG5 counts. Product schema 2; `null` for a version published
   * before it, which every currently published version is until the
   * Atlas is recomputed. Every consumer must handle the null. */
  buildingsByGrade: readonly number[] | null;
  /** Damage per IMS-25 type, heaviest first. Schema 2; `null` before. */
  buildingsByType: readonly RiskBuildingTypeDamage[] | null;
  typeCatalog: RiskTypeCatalog | null;
  /** Schema 2; `null` before. */
  populationByIntensity: RiskPopulationByIntensity | null;
}

/**
 * One `areas.json` level (D46 follow-up, `risk-areas` wave) — a SEPARATE,
 * finer-grained ranked-area product alongside `districts.json`'s single
 * ADM1 level: governorate (ADM1, same granularity `RiskDistrict` already
 * covers), district (ADM2), subdistrict (ADM3), and city (GHS urban-centre
 * points, not an OCHA admin level at all). Fixed set, fixed order — no
 * locale/producer is ever allowed to invent a fifth.
 */
export type RiskAreaLevel = "governorate" | "district" | "subdistrict" | "city";

/** One `areas.json` row, any level — deliberately the same field shape
 * `RiskDistrict` uses for its own per-area figures (coverage/buildings/
 * exposure), plus the identity fields (`id`, `name`, `level`, `parentId`)
 * a multi-level product needs that a single-level one (`RiskDistrict`)
 * doesn't. No casualty slot, same D45 rule every other risk-chain type in
 * this file follows. */
export interface RiskArea {
  /** OCHA COD-AB p-code (governorate/district/subdistrict) or GHS
   * urban-centre id (city) — the producer's own id space per level,
   * never renumbered app-side. */
  id: string;
  /** English name, as published — this product carries no localized
   * name field to translate through. */
  name: string;
  level: RiskAreaLevel;
  /** Parent area's own id, one level up — `null` only for a row with no
   * modeled parent (never actually emitted at today's four levels, since
   * even the top, `governorate`, carries its country p-code as parent;
   * kept nullable because the producer's own field is). */
  parentId: string | null;
  /** Fraction (0..1) of this area's building stock actually covered by
   * the exposure grid — same "a low value means a partial-coverage
   * undercount" reasoning `RiskDistrict.coverage`'s own doc comment
   * documents. */
  coverage: number;
  buildingsInGrid: number;
  buildingsHeavy: number;
  buildingsDg4Plus: number;
  /** `null` only when the product's own `n_draws` is `0` — a point
   * estimate with no Monte Carlo range to show alongside it, never
   * fabricated as `[value, value, value]`. */
  buildingsHeavyP05P50P95: readonly [number, number, number] | null;
  buildingsDg4PlusP05P50P95: readonly [number, number, number] | null;
  exposedPopulation: number;
  /** The area's name in the app's four locales, where the producer knows
   * them. The boundary datasets transliterate Iraqi place names through
   * Arabic, so the producer corrects them and ships the Kurdish forms
   * alongside. `null` when it has no entry for this area. */
  names: Readonly<Record<string, string>> | null;
  /** `false` when the producer's corrected spelling is its own proposal
   * rather than one from the owner's gazetteer. */
  nameVerified: boolean | null;
  /** DG0..DG5 for this area. Schema 2; `null` before it. */
  buildingsByGrade: readonly number[] | null;
  /** The full 26-type matrix at governorate level, the three most
   * damaged types below that. Schema 2; `null` before it. */
  damagedTypes: readonly RiskBuildingTypeDamage[] | null;
  populationByIntensity: RiskPopulationByIntensity | null;
}

/** Parsed `areas.json` — one event version's four-level ranked-area
 * product. Each level's row array is already producer-sorted worst-first
 * (same "never re-sort" contract `RiskDistricts.districts` documents),
 * independently per level. */
export interface RiskAreas {
  /** IMS-25 type metadata for every `RiskArea.damagedTypes` row below.
   * Schema 2; `null` before it. */
  typeCatalog: RiskTypeCatalog | null;
  /** Damage/fragility model id backing this product (e.g.
   * `"gl2004_macroseismic"`) — same "internal pipeline id, shown through a
   * translated name, never verbatim" treatment `RiskSummary.stage` gets
   * (`RiskProvenanceChips.tsx`'s `STAGE_NAME_KEYS`). */
  damageModel: string;
  timeOfDay: RiskTimeOfDay;
  nDraws: number;
  levels: Record<RiskAreaLevel, RiskArea[]>;
  /** Tolerant-parsing bookkeeping, same convention as `RiskDistricts.
   * skippedCount` — summed across all four levels, one bad row anywhere
   * never discards any other row. */
  skippedCount: number;
}

/** One `districts.json` row (one ADM1/province). */
export interface RiskDistrict {
  adm1Id: string;
  adm1Name: string;
  country: string;
  /** Fraction (0..1) of this district's building stock actually covered
   * by the exposure grid — a low value means the headline number for this
   * district is a partial-coverage undercount, not a confident total. */
  coverage: number;
  buildingsInGrid: number;
  buildingsHeavy: number;
  buildingsDg4Plus: number;
  buildingsHeavyP05P50P95: readonly [number, number, number];
  buildingsDg4PlusP05P50P95: readonly [number, number, number];
  exposedPopulation: number;
}

/** Parsed `districts.json` — already producer-sorted worst-first;
 * `parseRiskDistricts` preserves that order rather than re-sorting, since
 * `RiskSection`'s "first 8, then Show all" behavior depends on it. */
export interface RiskDistricts {
  stage: string;
  timeOfDay: RiskTimeOfDay;
  nDraws: number;
  districts: RiskDistrict[];
  /** Tolerant-parsing bookkeeping, same convention as
   * `IntensityContourSet.skippedCount` — a malformed district row is
   * dropped and counted, never a reason to discard every other row. */
  skippedCount: number;
}

/** One expected-damage-grade contour ring level (DG ramp index 1..5) —
 * the damage-chain sibling of `IntensityContourLevel`. */
export interface DamageContourLevel {
  value: number;
  /** `value` rounded and clamped to the DG ramp's 1..5 index range
   * (`damage-ramp.ts`) — the index into `theme.colors.damageGrade`. */
  level: number;
  rings: ContourRing[];
}

/** Parsed `cont_damage.json` — same shape/ordering contract as
 * `IntensityContourSet` (ascending by `value`, so a renderer painting in
 * order gets correct z-ordering for free). */
export interface DamageContourSet {
  levels: DamageContourLevel[];
  skippedCount: number;
}

/** The full risk product for one event version — `summary` and
 * `districts` are both required (a risk product with only one of the two
 * is treated as absent, `risk.ts`'s `parseRiskProduct`); `damageContours`
 * is optional since `risk_contours` is the one risk artifact `ShakeMapView`
 * can still work without (the intensity layer stays fully usable, just no
 * "Damage" toggle option). */
export interface RiskProduct {
  summary: RiskSummary;
  districts: RiskDistricts;
  damageContours: DamageContourSet | null;
  /** Optional `areas.json` product (`risk-areas` wave) — `null` for the
   * overwhelming majority of events that predate this product or whose
   * publish didn't carry one, same "absent, not fabricated" rule
   * `damageContours` already follows; unlike `damageContours`, an absent
   * `areas` never degrades anything else, `RiskSection` simply falls back
   * to the coarser `RiskProvinceList` (the `districts` product above) it
   * already rendered before this wave. */
  areas: RiskAreas | null;
  /** Absolute URL of this version's downloadable `report.pdf`
   * (`RiskProvenanceChips.tsx`'s "Download report" button, D46 follow-up).
   * `null` hides the button entirely — for a LIVE product this means the
   * `report` `shakemap_products` row genuinely wasn't published yet; for a
   * bundled product it is never null (`risk.ts`'s `buildBundledReportUrl`
   * derives it deterministically from the event id + version, the same
   * two values every bundled entry already carries). */
  reportUrl: string | null;
}
