// GENERATED by bumelerze-engine scripts/export_map_overlays.py — do not edit.
// Corners of public/data/vs30-site-class.png (Web Mercator rows), and the
// NEHRP site classes that actually occur in it.
export const VS30_OVERLAY_BOUNDS = {
  west: 33.6125,
  east: 55.545833,
  north: 43.9125,
  south: 26.2875,
} as const;
export const VS30_OVERLAY_CLASSES = ["B", "C", "D"] as const;
export const VS30_OVERLAY_SIZE = { width: 1316, height: 1303 } as const;
