#!/usr/bin/env python3
"""bundle_atlas_for_app — generator: reads
`shake-service/bumelerze-atlas/<id>/v<n>/{cont_mi.json,info.json}` for every
curated Historical View event (`src/features/historical/notable-events.ts`,
parsed the same way `seed_atlas.py` does — one source of truth) and writes
a trimmed per-event JSON + a static TS index into
`src/features/shakemap/atlas/` (D21 "Bumelerze Atlas ... app-side
bundling": "copy each atlas event's cont_mi.json + a trimmed metadata
record into src/features/shakemap/atlas/").

Re-run this after `seed_atlas.py` produces a NEW version for any of these
events (a revised historical map, a corrected engine run, ...) — it always
picks each event's LATEST version present on disk under
`bumelerze-atlas/`. This script does zero network I/O — it only reads
already-seeded local files.

`review_status`/`data_used` (D21 provenance-as-UI) are carried straight
through from each event's `info.json`, plus a coarse `dataUsedSummaryKey`
(`"catalogOnly" | "stationConditioned" | "dyfiConditioned" |
"stationAndDyfiConditioned"`) computed from the ACTUAL
`data_used["conditioning_applied"]` flags — NOT the coarser
`conditioning_sources` `seed_atlas.py` reports (which only records whether
station/DYFI data was *available*, not whether the small-N conditioning
floor was actually cleared; an event whose only observations fell below
the floor published the BARE prior and must be labelled `"catalogOnly"`
here, honestly, even though raw station/DYFI data existed).

Usage:
    ./.venv/bin/python scripts/bundle_atlas_for_app.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent))
import seed_atlas  # noqa: E402 -- reuses parse_notable_events, the one source of truth

SHAKE_SERVICE_ROOT = Path(__file__).resolve().parent.parent
REPO_ROOT = SHAKE_SERVICE_ROOT.parent
ATLAS_ROOT = SHAKE_SERVICE_ROOT / "bumelerze-atlas"
APP_ATLAS_DIR = REPO_ROOT / "src" / "features" / "shakemap" / "atlas"
APP_DATA_DIR = APP_ATLAS_DIR / "data"

_VERSION_DIR_RE = re.compile(r"v(\d+)")


def latest_version_dir(event_dir: Path) -> Path:
    versions = []
    for p in event_dir.iterdir():
        if p.is_dir():
            m = _VERSION_DIR_RE.fullmatch(p.name)
            if m:
                versions.append((int(m.group(1)), p))
    if not versions:
        raise ValueError(f"bundle_atlas_for_app: no version directory under {event_dir}")
    versions.sort(key=lambda pair: pair[0])
    return versions[-1][1]


def data_used_summary_key(data_used: dict[str, Any]) -> str:
    """See module docstring — honest w.r.t. the small-N conditioning
    floor: `"catalogOnly"` unless conditioning was ACTUALLY applied for at
    least one IMT."""
    applied = data_used.get("conditioning_applied") or {}
    if not any(applied.values()):
        return "catalogOnly"
    used_stations = (data_used.get("instrument_stations_parsed") or 0) > 0
    used_dyfi = (data_used.get("dyfi_boxes_parsed") or 0) > 0
    if used_stations and used_dyfi:
        return "stationAndDyfiConditioned"
    if used_stations:
        return "stationConditioned"
    return "dyfiConditioned"


def bundle_event(event_id: str) -> dict[str, Any]:
    event_dir = ATLAS_ROOT / event_id
    version_dir = latest_version_dir(event_dir)
    info = json.loads((version_dir / "info.json").read_text())
    contours = json.loads((version_dir / "cont_mi.json").read_text())
    return {
        "eventId": event_id,
        "producer": "bumelerze",
        "version": info["product_version"],
        "reviewStatus": info["review_status"],
        "dataUsedSummaryKey": data_used_summary_key(info["data_used"]),
        "generatedAt": info["generated_at"],
        "contours": contours,
    }


def _js_identifier(event_id: str) -> str:
    # Event ids are alnum (USGS/ISC-GEM convention); prefix with "atlas_"
    # so a numeric-leading id can never produce an invalid JS identifier.
    return "atlas_" + re.sub(r"[^a-zA-Z0-9_]", "_", event_id)


def write_index_ts(event_ids: list[str]) -> Path:
    lines: list[str] = [
        "/**",
        " * Bumelerze Atlas index (D21) — GENERATED by",
        " * shake-service/scripts/bundle_atlas_for_app.py — do not hand-edit.",
        " * Regenerate: ./.venv/bin/python scripts/bundle_atlas_for_app.py",
        " * (from shake-service/), after re-running seed_atlas.py.",
        " *",
        " * Maps every curated historical event id",
        " * (src/features/historical/notable-events.ts) to its bundled",
        " * bumelerze-shake-service product — raw cont_mi.json contours +",
        " * review_status + a data-used summary key, computed entirely",
        " * offline (shake-service/scripts/seed_atlas.py), zero network cost",
        " * at render time (D21: \"Displayed maps are ALWAYS",
        " * bumelerze-shake-service products\").",
        " */",
        'import type { AtlasBundleEntry } from "../types";',
        "",
    ]
    for event_id in event_ids:
        lines.append(f'import {_js_identifier(event_id)} from "./data/{event_id}.json";')
    lines.append("")
    lines.append("export const ATLAS_INDEX: Readonly<Record<string, AtlasBundleEntry>> = {")
    for event_id in event_ids:
        lines.append(f"  {json.dumps(event_id)}: {_js_identifier(event_id)} as unknown as AtlasBundleEntry,")
    lines.append("};")
    lines.append("")
    lines.append("export const ATLAS_EVENT_IDS: readonly string[] = Object.keys(ATLAS_INDEX);")
    lines.append("")

    out_path = APP_ATLAS_DIR / "index.ts"
    out_path.write_text("\n".join(lines))
    return out_path


def main() -> None:
    events = seed_atlas.parse_notable_events()
    APP_DATA_DIR.mkdir(parents=True, exist_ok=True)

    event_ids: list[str] = []
    for e in events:
        event_id = e["id"]
        bundle = bundle_event(event_id)
        out_path = APP_DATA_DIR / f"{event_id}.json"
        out_path.write_text(json.dumps(bundle, separators=(",", ":")))
        event_ids.append(event_id)
        print(f"wrote {out_path} (dataUsedSummaryKey={bundle['dataUsedSummaryKey']}, reviewStatus={bundle['reviewStatus']})")

    index_path = write_index_ts(event_ids)
    print(f"wrote {index_path}")


if __name__ == "__main__":
    main()
