#!/usr/bin/env python3
"""Builds src/features/share/share-font-data.ts: Vazirmatn Regular and Bold,
subset to Latin plus Arabic script and re-encoded as base64 woff2.

Why: on the web the share card is a standalone SVG rasterised through a canvas,
and an SVG used as an image cannot see the page's fonts. The two faces are
therefore embedded in the SVG itself as base64 @font-face rules. The data is
loaded only when someone shares an image (a dynamic import), never at startup.

Usage (needs fonttools and brotli; any virtualenv will do):

    pip install fonttools brotli
    python3 scripts/build-share-fonts.py

Vazirmatn is SIL OFL (assets/fonts/OFL-Vazirmatn.txt); subsetting and embedding
are permitted. All layout features are kept, because Arabic joining relies on them.
"""
import base64
import io
import pathlib

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS = ROOT / "assets" / "fonts"
OUT = ROOT / "src" / "features" / "share" / "share-font-data.ts"

# Basic Latin and Latin-1, general punctuation used in captions, Arabic, Arabic
# Supplement, Arabic Extended-A, presentation forms, and the bidi controls.
UNICODES = (
    list(range(0x0020, 0x007F))
    + list(range(0x00A0, 0x0100))
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x00B7]
    + list(range(0x0600, 0x0700))
    + list(range(0x0750, 0x0780))
    + list(range(0x08A0, 0x0900))
    + list(range(0xFB50, 0xFDFF))
    + list(range(0xFE70, 0xFF00))
    + list(range(0x200B, 0x2010))
    + list(range(0x2066, 0x206A))
)


def woff2_base64(path: pathlib.Path) -> str:
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["*"]
    options.notdef_outline = True
    options.name_IDs = [1, 2, 3, 4, 6]
    font = TTFont(str(path))
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    buffer = io.BytesIO()
    font.flavor = "woff2"
    font.save(buffer)
    return base64.b64encode(buffer.getvalue()).decode("ascii")


regular = woff2_base64(FONTS / "Vazirmatn-Regular.ttf")
bold = woff2_base64(FONTS / "Vazirmatn-Bold.ttf")

OUT.write_text(
    "/* GENERATED by scripts/build-share-fonts.py. Do not edit by hand.\n"
    " * Vazirmatn (SIL OFL), subset to Latin + Arabic script, woff2, base64. */\n\n"
    f'export const VAZIRMATN_REGULAR_WOFF2_BASE64 =\n  "{regular}";\n\n'
    f'export const VAZIRMATN_BOLD_WOFF2_BASE64 =\n  "{bold}";\n',
    encoding="utf-8",
)
print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KB)")
