/**
 * Bundled handbook data — GENERATED by
 * `shake-service/scripts/build_handbook_data.py`, do not hand-edit.
 * Regenerate: `./.venv/bin/python scripts/build_handbook_data.py` (from
 * `shake-service/`). Plain JSON module imports (Metro/TS `resolveJsonModule`
 * bundles these straight into the JS bundle) — same pattern
 * `features/shakemap/atlas/index.ts` uses for the Bumelerze Atlas, chosen
 * over the sqlite-asset pattern `features/catalog` uses because these three
 * files are small enough (~200 KB combined) to not need a native-module
 * database at all.
 */
import pgaZonesData from "./data/pga-zones.json";
import soilPointsData from "./data/soil-points.json";
import vs30GridData from "./data/vs30-grid.json";
import type { PgaZone, SoilPoint, Vs30Grid } from "./types";

export const PGA_ZONES = pgaZonesData as unknown as readonly PgaZone[];
export const VS30_GRID = vs30GridData as unknown as Vs30Grid;
export const SOIL_POINTS = soilPointsData as unknown as readonly SoilPoint[];
