/**
 * Bundled handbook data — GENERATED by
 * `bumelerze-engine/scripts/build_handbook_data.py`, do not hand-edit.
 * Regenerate: `./.venv/bin/python scripts/build_handbook_data.py` (from
 * `bumelerze-engine`). Plain JSON module imports (Metro/TS `resolveJsonModule`
 * bundles these straight into the JS bundle) — same pattern
 * `features/shakemap/atlas/index.ts` uses for the Bumelerze Atlas, chosen
 * over the sqlite-asset pattern `features/catalog` uses because these three
 * files are small enough (~230 KB combined) to not need a native-module
 * database at all.
 */
import isc2025DistrictsData from "./data/isc2025-districts.json";
import isc2025SsZonesData from "./data/isc2025-ss-zones.json";
import isc2025SurfaceData from "./data/isc2025-surface.json";
import isc2017ZonesData from "./data/isc2017-zones.json";
import pgaZonesData from "./data/pga-zones.json";
import soilPointsData from "./data/soil-points.json";
import vs30GridData from "./data/vs30-grid.json";
import type {
  Isc2017Zones,
  Isc2025District,
  Isc2025SsZone,
  Isc2025SurfaceModel,
  PgaZone,
  SoilPoint,
  Vs30Grid,
} from "./types";

export const PGA_ZONES = pgaZonesData as unknown as readonly PgaZone[];
export const VS30_GRID = vs30GridData as unknown as Vs30Grid;
export const SOIL_POINTS = soilPointsData as unknown as readonly SoilPoint[];

/** GENERATED by `bumelerze-engine/scripts/build_isc2025_hazard.py` from the
 * IMOS-2025 sources in the vault. Regenerate:
 * `./.venv/bin/python scripts/build_isc2025_hazard.py`. */
export const ISC2025_DISTRICTS = isc2025DistrictsData as unknown as readonly Isc2025District[];
export const ISC2025_SS_ZONES = isc2025SsZonesData as unknown as readonly Isc2025SsZone[];
export const ISC2025_SURFACE = isc2025SurfaceData as unknown as Isc2025SurfaceModel;

/** GENERATED by `bumelerze-engine/scripts/build_isc2017_hazard.py` from the
 * three digitised 2017 figures in the vault. Regenerate:
 * `./.venv/bin/python scripts/build_isc2017_hazard.py`. */
export const ISC2017_ZONES = isc2017ZonesData as unknown as Isc2017Zones;
